default_platform(:ios)

platform :ios do
  before_all do
    app_store_connect_api_key(
      key_id: "XGFA878VQB",
      issuer_id: "69a6de83-1bd1-47e3-e053-5b8c7c11a4d1",
      key_filepath: File.expand_path("~/.appstoreconnect/private/AuthKey_XGFA878VQB.p8"),
      in_house: false
    )
  end

  desc "Upload metadata to App Store Connect"
  lane :upload_metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true,
      precheck_include_in_app_purchases: false,
      app_review_information: {}
    )
  end

  desc "Upload screenshots to App Store Connect"
  lane :upload_screenshots do
    deliver(
      skip_binary_upload: true,
      skip_metadata: true,
      force: true,
      precheck_include_in_app_purchases: false
    )
  end
end
